### ISSUE TITLE
Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://local...

### ISSUE THREAD

**Issue by emettely** [ZotPlus/zotero-citations#6]
Please help, I just installed better bib text to get this going. Details are as follows:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [zotero-citations](https://github.com/ZotPlus/zotero-citations) package, v0.3.0

### Stack Trace

Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:23119/better-bibtex/schomd'.

```
At /Users/user/.atom/packages/zotero-citations/lib/zotero-citations.coffee:22

Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:23119/better-bibtex/schomd'.
  at Error (native)
  at Object.module.exports.ZoteroScan.bibliography (/Users/user/.atom/packages/zotero-citations/lib/zotero-citations.coffee:22:12)
  at Object.module.exports.ZoteroScan.scan (/Users/user/.atom/packages/zotero-citations/lib/zotero-citations.coffee:95:14)
  at atom-workspace.subscriptions.add.atom.commands.add.zotero-citations:scan (/Users/user/.atom/packages/zotero-citations/lib/zotero-citations.coffee:8:89)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -1:09.0 core:copy (div.package-readme.native-key-bindings)
     -1:04.7.0 core:paste (atom-text-editor.editor.is-focused)
     -1:03.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:46.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:46.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:10.9.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:09.0 core:undo (atom-text-editor.editor.is-focused)
     -0:06.4.0 core:redo (atom-text-editor.editor.is-focused)
     -0:04.2.0 zotero-citations:scan (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-bibtex, v0.6.0
markdown-toc, v0.3.0
markdown-writer, v1.9.0
zotero-citations, v0.3.0

# Dev
No dev packages
```

**Comment by retorquere** [comment]
Have you enabled 'Enable export by HTTP'?

**Comment by emettely** [comment]
Yes I have.
I have 2 plugins - one in standalone and one in firefox.
I have enabled for firefox.
However, for the standalone the setting does not exist or refuses to show.

**Comment by retorquere** [comment]
That's because in standalone the feature is always on. I can't reproduce
the error currently; do you experience this with bbt in Firefox or in
standalone (not simultaneously, BBT doesn't work in that mode)?

**Comment by igravious** [comment]
I got this error when Firefox was not open. Possibly as simple as that?

**Comment by retorquere** [comment]
That would do it, yes :)

**Comment by igravious** [comment]
:)
